---
title: "Collaborations"
subtitle: "Advisors, mentors, and long-running scientific relationships"
---

[Postdoctoral research]{.eyebrow}

### Indiana University

[Michael Wade](https://biology.indiana.edu/) was my postdoctoral advisor and an
evolutionary geneticist. I developed theory to understand the evolution of
transmission modes in coevolutionary interactions.

Curt Lively was just down the hall, and I regularly attended his lab meetings.
As a researcher using the New Zealand mud snail (*Potamopyrgus antipodarum*)
host-parasite system, we have many common interests.

## Graduate research

### Washington State University

Mark Dybdahl was one of my graduate advisors and an evolutionary ecologist. I
conducted my empirical research on *Potamopyrgus antipodarum* with Dr. Dybdahl.
He also contributed significantly to my theoretical projects.

Richard Gomulkiewicz was one of my graduate advisors and a theoretical
population geneticist. Dr. Gomulkiewicz mentored me on the theoretical portion
of my thesis.

[Michael Alfaro](https://www.eeb.ucla.edu/) (now at UCLA) was on my committee, a
molecular and theoretical phylogeneticist. I worked on molecular sequencing
projects covering wrasses (*Halichoeres*) and Tetraodontiformes.

## Pre-dissertation research

### Boston University

[Paul Barber](https://www.eeb.ucla.edu/) (now at UCLA) was one of my supervisors
while I was a research technician. I worked on several population genetic
studies of reef fish.

Phillip Lobel was one of my supervisors while I was a research technician. I
worked on a molecular study of parentage and mating system in a damselfish
(*Abudefduf sordidus*).

### University of Utah

Dale Clayton was my advisor at the University of Utah. I worked on the host
specificity of feather feeding lice on North American dove hosts.

Kevin Johnson (now at the University of Illinois) was a postdoc in Dr. Clayton's
lab. We worked on cophylogenetic methods and molecular ecology projects.

### Grinnell College

Jonathan (Jackie) Brown was my research advisor at Grinnell College. I conducted
a molecular systematics project on a family of cynipid gall wasps, the same ones
Alfred Kinsey worked on while at Indiana University.

Leslie Gregg-Jolly was my academic advisor at Grinnell College.

### University of Pittsburgh

Susan Kalisz was my supervisor while I was a technician. I worked on field and
greenhouse studies of plant mating system genetics.
